url = "https://medium.com/@robertgrosse/my-experience-rewriting-enjarify-in-rust-723089b406ad"
fetched_at = "2025-10-14T15:16:38.626712789-06:00[-06:00]"
status_code = 200
content_type = "text/html; charset=utf-8"
