url = "http://graydon2.dreamwidth.org/214016.html"
fetched_at = "2025-10-14T15:16:37.8413593-06:00[-06:00]"
status_code = 200
final_url = "https://graydon2.dreamwidth.org/214016.html"
content_type = "text/html; charset=utf-8"
