url = "http://blog.burntsushi.net/csv/"
fetched_at = "2025-10-14T15:16:34.784039424-06:00[-06:00]"
status_code = 200
final_url = "https://burntsushi.net/csv/"
content_type = "text/html; charset=utf-8"
