url = "http://graydon2.dreamwidth.org/218040.html"
fetched_at = "2025-10-14T15:16:38.379571241-06:00[-06:00]"
status_code = 200
final_url = "https://graydon2.dreamwidth.org/218040.html"
content_type = "text/html; charset=utf-8"
