url = "http://science.raphael.poss.name/rust-for-functional-programmers.html"
fetched_at = "2025-10-14T15:16:37.069203017-06:00[-06:00]"
status_code = 200
final_url = "https://dr-knz.net/rust-for-functional-programmers.html"
content_type = "text/html"
